version: '3.8'

services:
  mysql:
    build: ..
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jobportal
      MYSQL_USER: jobportal
      MYSQL_PASSWORD: jobportal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: