apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-broker
  template:
    metadata:
      labels:
        app: rabbitmq-broker
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13-management
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-broker-service
spec:
  selector:
    app: rabbitmq-broker
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: management
    protocol: TCP
    port: 15672
    targetPort: 15672